include: package:very_good_analysis/analysis_options.6.0.0.yaml


# Configures the Dart formatter settings so that you do not have to set line length 100 every time.
formatter:
  page_width: 100

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    eol_at_end_of_file: false
    require_trailing_commas: true

# Add specific ignores for generated files
analyzer:
  exclude:
    - lib/l10n/arb/app_localizations.dart
  plugins:
    - custom_lint

# Configure custom lint rules
custom_lint:
  rules:
    - avoid_debug_print
    - avoid_log