[build]
command = """
    FLUTTER_VERSION="3.32.0"
    curl -fSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -o flutter.tar.xz
    tar xf flutter.tar.xz
    export PATH="$PWD/flutter/bin:$PATH"
    # Install dependencies for the Netlify Function
    cd netlify/functions
    npm install
    cd ../..
    # Continue with the Flutter build
    flutter config --enable-web
    flutter precache --web 
    flutter pub get
    # Note: Web does not support flavor, we can do it via target or dart-define or both
    # https://github.com/flutter/flutter/issues/59388
    # web itself has no concept of flavors but 3 workarounds
    # dart defines, sep targets, sep index.htmls etc
    # Note: diff env variable MEMVERSE_API_KEY for now, check netlify UI
    flutter build web --dart-define=MEMVERSE_CLIENT_API_KEY=$MEMVERSE_API_KEY --release --dart-define=CLIENT_ID=$MEMVERSE_CLIENT_ID --dart-define=POSTHOG_MEMVERSE_API_KEY=$POSTHOG_MEMVERSE_API_KEY --target lib/main_production.dart
  """
publish = "build/web"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true