[build]
command = """
    FLUTTER_VERSION="3.29.3" # Specify Flutter 3.29.3
    curl -fSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -o flutter.tar.xz
    tar xf flutter.tar.xz
    export PATH="$PWD/flutter/bin:$PATH"
    # Install dependencies for the Netlify Function
    cd netlify/functions
    npm install
    cd ../..
    # Continue with the Flutter build
    flutter config --enable-web
    flutter precache --web 
    flutter pub get 
    flutter build web --release --dart-define=CLIENT_ID=$MEMVERSE_CLIENT_ID --target lib/main_development.dart
  """
publish = "build/web"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true