[build]
command = """
    FLUTTER_VERSION="3.29.3" # Specify Flutter 3.29.3
    curl -fSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -o flutter.tar.xz
    tar xf flutter.tar.xz
    export PATH="$PWD/flutter/bin:$PATH"
    flutter config --enable-web
    flutter pub get # Ensure dependencies are fetched
    flutter build web --release
  """
publish = "build/web"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true