name: memverse
description: Scripture Memory mobile front end for www.memverse.com
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.7.2
  flutter: 3.29.2

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  intl: 0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  bdd_widget_test: 1.8.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  mocktail: 1.0.4
  riverpod_generator: ^2.6.5
  very_good_analysis: 7.0.0

flutter:
  uses-material-design: true
  generate: true