name: memverse
description: Scripture Memory mobile front end for www.memverse.com
version: 0.1.2+30.a3cb3a3
publish_to: none

environment:
  sdk: 3.7.2
  flutter: 3.29.3 # Needs to match FLUTTER_VERSION in scripts/project_config.sh

dependencies:
  dio: 5.8.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  http: ^1.1.0
  intl: 0.19.0
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  bdd_widget_test: 1.8.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  mocktail: 1.0.4
  network_image_mock: ^2.1.1
  patrol: ^3.15.1
  patrol_finders: ^2.7.2
  riverpod_generator: ^2.6.5
  very_good_analysis: 7.0.0

# Custom scripts for common tasks
scripts:
  test: flutter test
  test_coverage: flutter test --coverage
  clean_coverage: lcov --remove coverage/lcov.info 'lib/l10n' '**/*.g.dart' -o coverage/new_lcov.info
  gen_coverage_html: genhtml coverage/new_lcov.info -o coverage/html
  coverage: flutter test --coverage && lcov --remove coverage/lcov.info 'lib/l10n' '**/*.g.dart' -o coverage/new_lcov.info && genhtml coverage/new_lcov.info -o coverage/html
  format: dart format . -l 100
  analyze: flutter analyze
  fix: dart fix --apply
  test_live_login: flutter test integration_test/live_login_test.dart --flavor development --dart-define=USERNAME=$MEMVERSE_USERNAME --dart-define=PASSWORD=$MEMVERSE_PASSWORD --dart-define=CLIENT_ID=$MEMVERSE_CLIENT_ID
  integration_test: flutter test integration_test

flutter:
  uses-material-design: true
  generate: true