name: memverse
description: Scripture Memory mobile front end for www.memverse.com
version: 0.1.2+60.e68da18
publish_to: none

environment:
  sdk: 3.7.2
  flutter: 3.29.3 # Needs to match FLUTTER_VERSION in scripts/project_config.sh

dependencies:
  dio: 5.8.0+1
  feedback: 3.1.0
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_secure_storage: 9.2.4
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  http: 1.3.0
  intl: 0.19.0
  json_annotation: ^4.9.0
  logger: 2.5.0
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  share_plus: 11.0.0

dev_dependencies:
  bdd_widget_test: 1.8.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mockito: ^5.4.5
  mocktail: 1.0.4
  network_image_mock: ^2.1.1
  path_provider_platform_interface: ^2.1.2
  patrol: ^3.15.1
  patrol_finders: ^2.7.2
  plugin_platform_interface: ^2.1.8
  riverpod_generator: ^2.6.5
  test_api: any
  very_good_analysis: 7.0.0

scripts:
  test: flutter test
  test_coverage: flutter test --coverage
  clean_coverage: lcov --remove coverage/lcov.info 'lib/l10n' '**/*.g.dart' -o coverage/new_lcov.info
  gen_coverage_html: genhtml coverage/new_lcov.info -o coverage/html
  coverage: flutter test --coverage && lcov --remove coverage/lcov.info 'lib/l10n' '**/*.g.dart' -o coverage/new_lcov.info && genhtml coverage/new_lcov.info -o coverage/html
  format: dart format . -l 100
  analyze: flutter analyze
  fix: dart fix --apply
  test_live_login: flutter test integration_test/live_login_test.dart --flavor development --dart-define=USERNAME=$MEMVERSE_USERNAME --dart-define=PASSWORD=$MEMVERSE_PASSWORD --dart-define=CLIENT_ID=$MEMVERSE_CLIENT_ID
  integration_test: flutter test integration_test

flutter:
  uses-material-design: true
  generate: true