name: memverse
description: Scripture Memory mobile front end for www.memverse.com
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.7.0
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  bdd_widget_test: 1.8.1
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: 7.0.0

flutter:
  uses-material-design: true
  generate: true
