name: memverse_lints
description: Custom lint rules for the Memverse project.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.11.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.1