// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0c0xAOPLiGLd-RzOCJI288w6DfGk4ec',
    appId: '1:1098987465855:web:714c0f030ea2857f82234a',
    messagingSenderId: '1098987465855',
    projectId: 'memverse-proj',
    authDomain: 'memverse-proj.firebaseapp.com',
    storageBucket: 'memverse-proj.firebasestorage.app',
    measurementId: 'G-V90YF9M80G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvotIO5J96Nh3VGvBuTpmzduvYPFakiM',
    appId: '1:1098987465855:android:8dd366c84114af7682234a',
    messagingSenderId: '1098987465855',
    projectId: 'memverse-proj',
    storageBucket: 'memverse-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5ZHGiqBvJcKYPQhuUf7y0ZBn6rLnrF0',
    appId: '1:1098987465855:ios:40c7bb494f85438482234a',
    messagingSenderId: '1098987465855',
    projectId: 'memverse-proj',
    storageBucket: 'memverse-proj.firebasestorage.app',
    iosBundleId: 'com.spiritflightapps.memverse',
  );

}