name: Deploy to Firebase Hosting

on:
  push:
    tags:
      - "firebase-deploy"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - name: Install dependencies
        run: |
          flutter pub get
          npm install -g firebase-tools
      - name: Build web app
        run: flutter build web --web-renderer canvaskit
        env:
          MEMVERSE_API_TOKEN: ${{ secrets.MEMVERSE_API_TOKEN }}
      - name: Deploy to Firebase
        run: |
          firebase use --token ${{ secrets.FIREBASE_TOKEN }} ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}